/* Rasgos de 🧱 BLOQUE BAJO — orden y muralla.
   Tres ramas: firma (profundiza lo propio) · respuesta (cubre el matchup débil)
   · expansión (abre un fútbol lateral). El nivel de desbloqueo y el costo salen
   del tier (ver TRAIT_LEVEL / TRAIT_COST en ./index.js). */

export const TRAITS_BLOQUE = [
  /* Firma · el área como fortaleza */
  {
    id: "compactacion", filo: "bloque", rama: "firma", tier: "basic", icon: "🏰",
    nombre: "Compactación",
    desc: "El bloque se cierra y le tapa el carril del medio: por el centro no se pasa, y al rival solo le queda dar la vuelta por afuera.",
    momento: "El rival dando vueltas por afuera sin encontrar la puerta.",
    req: {}, pos: { x: 190, y: 140 },
    hooks: { oppShotMalus: { seq: "repliegue", bonus: -0.05,
      texto: "El centro está clausurado: el remate llegó incómodo, forzado desde afuera." } },
  },
  {
    id: "sobrepoblado", filo: "bloque", rama: "firma", tier: "basic", icon: "🕸️",
    nombre: "Sobrepoblado",
    desc: "Hay siempre una pierna más de la que el rival contaba: los pases entre líneas se topan con alguien y el ataque muere antes de nacer.",
    momento: "El pase rival que no llega a destino tres veces seguidas.",
    req: {}, pos: { x: 190, y: 250 },
    hooks: { oppLoseActs: { p: 0.25,
      texto: "Zona sobrepoblada: el pase entre líneas se topa con una pierna y el ataque muere en la nada." } },
  },
  {
    id: "area_blindada", filo: "bloque", rama: "firma", tier: "intermediate", icon: "🗿",
    nombre: "Área Blindada",
    desc: "Dentro del área manda el equipo: cada centro se come, cada remate sale a destiempo y el rival termina buscando desde afuera.",
    momento: "El despeje número diez del central y la contra que nace de ahí.",
    req: { todos: ["compactacion", "sobrepoblado"] },
    pos: { x: 450, y: 195 },
    hooks: {
      deepBloque: {},
      boxShield: { bonus: -0.05,
        texto: "El área blindada: le achicaron el ángulo y el remate salió sin destino." },
    },
  },
  {
    id: "defensa_escalonada", filo: "bloque", rama: "firma", tier: "advanced", icon: "🪜",
    nombre: "Defensa Escalonada",
    desc: "Las líneas se escalonan: al que rompe la primera lo espera la segunda. El rival tarda medio partido en entender por dónde entrar.",
    momento: "La primera llegada rival muriendo contra una línea que ya estaba ahí.",
    req: { previo: "area_blindada" },
    pos: { x: 710, y: 125 },
    hooks: { firstChanceGuard: { bonus: -0.06,
      texto: "Primera llegada del partido y ya estaban escalonados: el que rompió la primera línea se encontró con la segunda." } },
  },
  {
    id: "muralla", filo: "bloque", rama: "firma", tier: "advanced", icon: "🧱",
    nombre: "Muralla",
    desc: "Mientras el marcador no vaya en contra, la zaga juega con una convicción distinta: nadie se saca la camiseta de encima y no pasa nadie.",
    momento: "Los últimos veinte minutos defendiendo el resultado sin conceder una sola llegada limpia.",
    req: { previo: "area_blindada" },
    pos: { x: 710, y: 245 },
    hooks: { wall: { bonus: -0.05,
      texto: "La muralla no se mueve: mientras el resultado aguante, por acá no pasa nadie." } },
  },
  {
    id: "fortaleza_inexpugnable", filo: "bloque", rama: "firma", tier: "master", icon: "👑",
    nombre: "Fortaleza Inexpugnable",
    desc: "El rival puede tener la pelota todo el partido: no va a tener una sola ocasión clara. Ataca, ataca, y termina discutiendo entre ellos.",
    momento: "El delantero rival discutiendo con sus compañeros tras la enésima llegada muerta.",
    req: { alguno: ["defensa_escalonada", "muralla"] },
    pos: { x: 960, y: 185 },
    hooks: {
      clearChanceGuard: { p: 0.25,
        texto: "¡No hay ocasión clara contra esta fortaleza! Apareció el que tenía que aparecer y la jugada murió sin remate." },
      oppPoolMod: { vsFilo: "posesion", weights: { repliegue: 0.74 } },
      frustration: { perShot: 0.02, cap: 0.08,
        texto: "La frustración rival se palpa: cuanto más ataca sin premio, peor remata — la muralla come moral." },
    },
  },

  /* Respuesta · sobrevivir al asedio */
  {
    id: "dominio_aereo", filo: "bloque", rama: "respuesta", tier: "basic", icon: "🦅",
    nombre: "Dominio Aéreo",
    desc: "Todo lo que entra por el aire lo gana el equipo: centros, córners y pelotas divididas terminan siempre en una cabeza propia.",
    momento: "El central ganando el décimo cabezazo del partido.",
    req: {}, pos: { x: 190, y: 395 },
    hooks: { aerialDef: { bonus: -0.05,
      texto: "Por arriba no se les gana: el cabezazo rival salió forzado, con la zaga encima." } },
  },
  {
    id: "atentos", filo: "bloque", rama: "respuesta", tier: "intermediate", icon: "👀",
    nombre: "Atentos",
    desc: "Tras cada atajada y cada bloqueo, la segunda pelota es del equipo: nadie mira la jugada, todos van al rechace.",
    momento: "El rechace del córner que ya es un pelotazo nuestro.",
    req: { previo: "dominio_aereo" },
    pos: { x: 450, y: 380 },
    hooks: {
      chainOnDefendSp: { to: "pelotazo", p: 0.30, bonus: 0.03,
        intro: p => `¡Atentos al rechace! La segunda pelota es nuestra y ${p.name} ya tiene el pelotazo armado.` },
      chainOnDuelFail: { to: "pelotazo", p: 0.30, bonus: 0.02,
        intro: p => `¡Atentos! El rechace del duelo cae al pie y ${p.name} vuelve a la carga.` },
    },
  },
  {
    id: "pelotazo_fuera", filo: "bloque", rama: "respuesta", tier: "advanced", icon: "🚀",
    nombre: "Pelotazo",
    desc: "Desbloquea la jugada Reventar el Balón: cuando el peligro aprieta, la zaga la manda lejos y obliga al rival a empezar todo de nuevo desde atrás.",
    momento: "El pelotazo a la tribuna que apaga el incendio y hace bramar al estadio.",
    req: { previo: "atentos" },
    pos: { x: 710, y: 360 },
    hooks: { clearBall: { zone: [1, 3], p: 0.30,
      texto: "¡A REVENTARLA! La zaga la manda lejos del área y el rival tiene que armar todo otra vez desde atrás." } },
  },
  {
    id: "al_area", filo: "bloque", rama: "respuesta", tier: "advanced", icon: "🎪",
    nombre: "Al Área",
    desc: "Desbloquea la jugada Saque Largo al Área: los saques de banda en campo rival dejan de ser un trámite y se convierten en un envío al área.",
    momento: "El saque de banda que termina en un córner a favor.",
    req: { previo: "atentos" },
    pos: { x: 710, y: 480 },
    hooks: { beachhead: { zone: [4, 5], p: 0.42,
      texto: "¡Saque largo AL ÁREA! La pelota salió por el lateral y el envío vuelve a llenar el área rival." } },
  },
  {
    id: "hombre_objetivo", filo: "bloque", rama: "respuesta", tier: "master", icon: "👑",
    nombre: "Hombre Objetivo",
    desc: "Desbloquea la jugada Pivoteo al Área: el nueve ya no solo cabecea, también la baja para el que llega de frente al arco.",
    momento: "El nueve aguantando de espaldas y la descarga que termina en gol.",
    req: { alguno: ["pelotazo_fuera", "al_area"] },
    pos: { x: 960, y: 420 },
    hooks: { pivot: { zone: [4, 5], bonus: 0.08,
      texto: "El hombre objetivo la aguanta de espaldas y la BAJA: llega uno de frente al arco." } },
  },

  /* Expansión · las armas del que defiende */
  {
    id: "especialistas", filo: "bloque", rama: "expansion", tier: "basic", icon: "📐",
    nombre: "Especialistas",
    desc: "El equipo tiene pateadores de verdad: cada centro de pelota quieta cae donde tiene que caer.",
    momento: "El córner que cae clavado en la cabeza del nueve.",
    req: {}, pos: { x: 280, y: 600 },
    hooks: { setpieceRehearsed: { bonus: 0.06, poolMult: 1,
      texto: "Esto lo patea un especialista: la pelota quieta cae exactamente donde se ensayó." } },
  },
  {
    id: "estrategia_ensayada", filo: "bloque", rama: "expansion", tier: "intermediate", icon: "📋",
    nombre: "Estrategia Ensayada",
    desc: "La pizarra del balón parado se ensaya toda la semana: córners y tiros libres laterales terminan en remate mucho más seguido.",
    momento: "Tres córners seguidos que terminan los tres en remate.",
    req: { previo: "especialistas" },
    pos: { x: 490, y: 600 },
    hooks: { poolMod: { weights: { balon_parado: 1.15 } } },
  },
  {
    id: "salida_vertical", filo: "bloque", rama: "expansion", tier: "advanced", icon: "📈",
    nombre: "Salida Vertical",
    desc: "Recuperada la pelota, el equipo no la esconde: la primera intención es siempre hacia adelante, y esos pases salen.",
    momento: "El pase vertical inmediato tras el robo, con el rival todavía volviendo.",
    req: { previo: "estrategia_ensayada" },
    pos: { x: 720, y: 600 },
    hooks: { transitionPass: { bonus: 0.05,
      texto: "Salida vertical: la pelota sale limpia hacia adelante antes de que el rival vuelva a su sitio." } },
  },
  {
    id: "contragolpe_letal", filo: "bloque", rama: "expansion", tier: "master", icon: "👑",
    nombre: "Contragolpe Letal",
    desc: "Desbloquea la jugada Contraataque: cada pelota recuperada en campo propio puede lanzarse de inmediato, sin pasar por armar el ataque.",
    momento: "El robo en la puerta del área propia que termina en gol en la de enfrente.",
    req: { previo: "salida_vertical" },
    pos: { x: 960, y: 600 },
    hooks: { chainOnContain: { to: "transicion", p: 0.30, bonus: 0.04,
      intro: p => `¡CONTRAATAQUE! Recuperaron en campo propio y ${p.name} sale disparado sin pedirle permiso a nadie.` } },
  },
];
