/* Rasgos de ⚡ CONTRAGOLPE — atacar el espacio.
   Tres ramas: firma (profundiza lo propio) · respuesta (cubre el matchup débil)
   · expansión (abre un fútbol lateral). El nivel de desbloqueo y el costo salen
   del tier (ver TRAIT_LEVEL / TRAIT_COST en ./index.js). */

export const TRAITS_CONTRA = [
  /* Firma · la contra misma */
  {
    id: "primer_pase", filo: "contra", rama: "firma", tier: "basic", icon: "📡",
    nombre: "Primer Pase",
    desc: "El primer pase tras recuperar la pelota no se piensa: sale hacia adelante y sale bien. La contra nace ya lanzada.",
    momento: "El pase que sale en el mismo movimiento del robo.",
    req: {}, pos: { x: 190, y: 150 },
    hooks: { transitionPass: { act: "first", bonus: 0.05,
      texto: "El primer pase salió al toque: la contra nace lanzada, sin escala de seguridad." } },
  },
  {
    id: "primera_marcha", filo: "contra", rama: "firma", tier: "intermediate", icon: "📈",
    nombre: "Primera Marcha",
    desc: "Ya en carrera, el equipo se entiende: los pases de la contra encuentran siempre al que va lanzado.",
    momento: "Tres pases a toda velocidad sin que la pelota toque el piso dos veces.",
    req: { previo: "primer_pase" },
    pos: { x: 450, y: 125 },
    hooks: { transitionPass: { bonus: 0.05,
      texto: "Primera marcha metida: la contra circula a toda velocidad y ningún pase se cae." } },
  },
  {
    id: "ataque_espacio", filo: "contra", rama: "firma", tier: "intermediate", icon: "🏃",
    nombre: "Ataque al Espacio",
    desc: "Cuando uno arranca, arrancan tres: el que conduce siempre tiene a quién buscar en carrera.",
    momento: "Tres contra dos y definición cruzada.",
    req: { previo: "primer_pase" },
    pos: { x: 450, y: 250 },
    hooks: { finishSupport: { of: "transicion", bonus: 0.06,
      texto: "Los desmarques al espacio parten a la defensa: hay dos camisetas libres esperando el pase." } },
  },
  {
    id: "ataque_relampago", filo: "contra", rama: "firma", tier: "advanced", icon: "⚡",
    nombre: "Ataque Relámpago",
    desc: "Del robo al remate en el menor número de pases posible: la jugada se resuelve antes de que el rival vuelva a estar en su sitio.",
    momento: "Robo, pase, gol: ocho segundos.",
    req: { todos: ["primera_marcha", "ataque_espacio"] },
    pos: { x: 700, y: 190 },
    hooks: {
      skipToFinish: { of: "transicion", p: 0.30, bonus: 0.05,
        intro: p => `¡Sin escalas! ${p.name} sale disparado: la contra se juega a UNA.` },
      deepContra: {},
    },
  },
  {
    id: "duelista", filo: "contra", rama: "firma", tier: "master", icon: "👑",
    nombre: "Duelista",
    desc: "En cada contra hay un jugador que se suelta solo: el equipo lo busca siempre, y el mano a mano es el desenlace natural.",
    momento: "El delantero solo contra el arquero, otra vez.",
    req: { previo: "ataque_relampago" },
    pos: { x: 940, y: 130 },
    hooks: { accelFinish: { of: "transicion", p: 0.30, bonus: 0.07,
      intro: p => `¡${p.name} se suelta de la marca y ya no lo agarra nadie: MANO A MANO con el arquero!` } },
  },
  {
    id: "el_enjambre", filo: "contra", rama: "firma", tier: "master", icon: "👑",
    nombre: "El Enjambre",
    desc: "La contra ya no la corren dos: la corren cinco. Cuando la pelota llega al área, la defensa rival no sabe a quién marcar.",
    momento: "Cuatro camisetas cruzando mediocampo a la vez.",
    req: { previo: "ataque_relampago" },
    pos: { x: 940, y: 265 },
    hooks: {
      supportUpgrade: { bonus: 0.05,
        texto: "El enjambre llegó entero: el pase encuentra al mejor rematador completamente libre." },
      avalancha: { bonus: 0.06,
        texto: "AVALANCHA a campo abierto: la contra llega en oleada y la defensa no sabe a quién marcar." },
    },
  },

  /* Respuesta · el precio de correr, y cómo fabricarse la contra */
  {
    id: "anaerobicos", filo: "contra", rama: "respuesta", tier: "basic", icon: "🫁",
    nombre: "Anaeróbicos",
    desc: "El equipo está hecho para el esfuerzo explosivo: salir a apretar y volver a correr le cuesta menos que a cualquiera.",
    momento: "La cuarta ráfaga de presión del partido, corrida igual que la primera.",
    req: {}, pos: { x: 190, y: 395 },
    hooks: { pressStamina: { factor: 0.85 } },
  },
  {
    id: "defensa_intencionada", filo: "contra", rama: "respuesta", tier: "intermediate", icon: "🪖",
    nombre: "Defensa Intencionada",
    desc: "El despeje de cabeza deja de ser un manotazo de ahogado: el central cabecea buscando a un compañero, y ahí ya empezó la contra.",
    momento: "El cabezazo del central que termina en gol treinta metros más allá.",
    req: { previo: "anaerobicos" },
    pos: { x: 430, y: 350 },
    hooks: { chainOnDefendSp: { to: "transicion", p: 0.30, bonus: 0.04,
      intro: p => `¡El despeje fue un PASE! ${p.name} la baja de cabeza y el equipo sale de contra con el rival entero arriba.` } },
  },
  {
    id: "el_anzuelo", filo: "contra", rama: "respuesta", tier: "intermediate", icon: "🎣",
    nombre: "El Anzuelo",
    desc: "El equipo tiene la pelota en su propio campo y espera: el rival, aburrido de mirar, termina saliendo a buscarla — y eso es exactamente lo que se quería.",
    momento: "El rival dando dos pasos afuera de su bloque y el espacio a su espalda abierto de par en par.",
    req: { previo: "anaerobicos" },
    pos: { x: 430, y: 455 },
    hooks: {
      oppPoolMod: { weights: { salida_fondo: 1.20 } },
      poolMod: { vsFilo: ["contra", "bloque"], weights: { transicion: 1.67 } },
      baitConvert: { vsFilo: ["contra", "bloque"], p: 0.30, bonus: 0.05,
        texto: "¡Picaron el ANZUELO! El rival dio dos pasos afuera y el espacio a su espalda es una autopista." },
    },
  },
  {
    id: "segundo_aire", filo: "contra", rama: "respuesta", tier: "advanced", icon: "💨",
    nombre: "Segundo Aire",
    desc: "En el tramo final del partido, cuando todos arrastran las piernas, los que corren la contra encuentran un aire que el rival ya no tiene.",
    momento: "El minuto ochenta y cinco, y el que arranca la contra es el que más corrió.",
    req: { todos: ["defensa_intencionada", "el_anzuelo"] },
    pos: { x: 680, y: 405 },
    hooks: { tiredLegs: { under: 50, bonus: 0.08,
      texto: "Piernas fundidas y ahí va igual: el segundo aire aparece justo cuando el rival ya no tiene ninguno." } },
  },
  {
    id: "skiller", filo: "contra", rama: "respuesta", tier: "master", icon: "👑",
    nombre: "Skiller",
    desc: "Al que conduce la contra no lo frena nadie de pie: el rival tiene que elegir entre dejarlo pasar o cometerle la falta.",
    momento: "La falta desesperada al borde del área, y el tiro libre es nuestro.",
    req: { previo: "segundo_aire" },
    pos: { x: 930, y: 405 },
    hooks: { counterFouls: { plus: 0.06,
      texto: "No lo pueden frenar limpio: al que corre la contra hay que hacerle falta." } },
  },

  /* Expansión · de dónde NACE la contra */
  {
    id: "estoicos", filo: "contra", rama: "expansion", tier: "basic", icon: "🗿",
    nombre: "Estóicos",
    desc: "Replegado, el equipo aguanta lo que le tiren: cede terreno sin ceder el área, y espera su momento.",
    momento: "El rival estrellándose contra el bloque una y otra vez.",
    req: {}, pos: { x: 280, y: 600 },
    hooks: { containBonus: { bonus: 0.05,
      texto: "El bloque aguanta estoico: cortan la jugada sin despeinarse." } },
  },
  {
    id: "balonazo", filo: "contra", rama: "expansion", tier: "intermediate", icon: "🌩️",
    nombre: "Balonazo",
    desc: "Una pelota que cruza el cielo del área propia es una contra en potencia: el equipo la disputa pensando ya en el arco de enfrente.",
    momento: "El rechace del duelo aéreo que cae al pie y ya son cuatro corriendo.",
    req: { previo: "estoicos" },
    pos: { x: 500, y: 545 },
    hooks: { chainOnDuelFail: { to: "transicion", p: 0.28, bonus: 0.04,
      intro: p => `¡La segunda pelota fue nuestra! ${p.name} la engancha y sale disparado con el rival mal parado.` } },
  },
  {
    id: "saque_rapido", filo: "contra", rama: "expansion", tier: "intermediate", icon: "⏱️",
    nombre: "Saque Rápido",
    desc: "Reventarla ya no es rendirse: el equipo reinicia antes de que el rival se acomode, y la jugada que parecía muerta sale corriendo para el otro lado.",
    momento: "El despeje que el rival mira caer mientras dos ya salieron corriendo.",
    req: { previo: "estoicos" },
    pos: { x: 500, y: 648 },
    hooks: { quickRestart: { p: 0.30, bonus: 0.04,
      intro: p => `¡SAQUE RÁPIDO! La reiniciaron antes de que el rival volviera: ${p.name} ya está corriendo.` } },
  },
  {
    id: "pase_atras", filo: "contra", rama: "expansion", tier: "advanced", icon: "🎯",
    nombre: "Pase Atrás",
    desc: "Desbloquea la jugada Pase Atrás: llegado al área, el que conduce no remata — la pisa y la devuelve para el que entra de frente al arco.",
    momento: "La pisada en el área chica y el compañero entrando solo a empujarla.",
    req: { todos: ["balonazo", "saque_rapido"] },
    pos: { x: 720, y: 600 },
    hooks: { squarePass: { bonus: 0.14,
      texto: "La pisa y la devuelve atrás: el que llega la empuja de frente al arco." } },
  },
  {
    id: "sin_escalas", filo: "contra", rama: "expansion", tier: "master", icon: "👑",
    nombre: "Sin Escalas",
    desc: "A veces no hay jugada: hay un pase y un jugador solo contra el arquero. El equipo entero juega esperando ese momento.",
    momento: "Un pase, cincuenta metros, y el nueve de cara al arquero.",
    req: { previo: "pase_atras" },
    pos: { x: 940, y: 600 },
    hooks: { oneOnOne: { p: 0.14, bonus: 0.12,
      intro: p => `¡SIN ESCALAS! Un solo pase y ${p.name} quedó MANO A MANO con el arquero: no hubo jugada, hubo puñalada.` } },
  },
];
