/* Rasgos de 🎼 POSESIÓN — tener y circular.
   Tres ramas: firma (profundiza lo propio) · respuesta (cubre el matchup débil)
   · expansión (abre un fútbol lateral). El nivel de desbloqueo y el costo salen
   del tier (ver TRAIT_LEVEL / TRAIT_COST en ./index.js). */

export const TRAITS_POSESION = [
  /* Firma · perfeccionar la estructura ofensiva */
  {
    id: "buen_pie", filo: "posesion", rama: "firma", tier: "basic", icon: "🦶",
    nombre: "Buen Pie",
    desc: "El pase de seguridad deja de ser un trámite: el equipo lo da bien incluso con la presión encima, y una pelota que parecía perdida vuelve a ser suya.",
    momento: "El pase interceptado que igual termina en un pie propio.",
    req: {}, pos: { x: 190, y: 200 },
    hooks: { recycleBuild: { p: 0.35,
      texto: "Buen pie: la pelota rebota y vuelve a ser nuestra — la jugada no se muere ahí." } },
  },
  {
    id: "tercer_hombre", filo: "posesion", rama: "firma", tier: "intermediate", icon: "🔺",
    nombre: "El Tercer Hombre",
    desc: "Las combinaciones de tres jugadores rompen líneas y aseguran la salida bajo presión: siempre aparece uno más para recibir.",
    momento: "La pared que deja atrás a toda la primera línea de presión.",
    req: { previo: "buen_pie" },
    pos: { x: 450, y: 200 },
    hooks: { playoutRescue: { p: 0.40,
      texto: "El tercer hombre salva la salida: el pase interceptado encuentra al desmarcado y el regalo no existe." } },
  },
  {
    id: "pitagoricos", filo: "posesion", rama: "firma", tier: "advanced", icon: "📐",
    nombre: "Pitagóricos",
    desc: "El equipo triangula con los ojos cerrados: cuando hay que elegir a quién buscar, siempre encuentra al que de verdad está mejor parado.",
    momento: "La triangulación que deja al mejor ubicado solo frente al arco.",
    req: { previo: "tercer_hombre" },
    pos: { x: 710, y: 128 },
    hooks: { supportUpgrade: { bonus: 0.05,
      texto: "Geometría pura: el triángulo encuentra al mejor ubicado de verdad, no al más cercano." } },
  },
  {
    id: "osciladores", filo: "posesion", rama: "firma", tier: "advanced", icon: "🌊",
    nombre: "Osciladores",
    desc: "El equipo mueve el balón de un lado al otro hasta que la presión rival se parte: cada cambio de orientación deja la jauría corriendo el carril equivocado.",
    momento: "El cambio de cuarenta metros con los tres que venían a presionar mirando cómo pasa por arriba.",
    req: { previo: "tercer_hombre" },
    pos: { x: 710, y: 275 },
    hooks: { poolMod: { vsFilo: "press", weights: { circulacion: 1.39 } } },
  },
  {
    id: "maquina_colectiva", filo: "posesion", rama: "firma", tier: "master", icon: "👑",
    nombre: "La Máquina Colectiva",
    desc: "Once jugadores moviéndose como una sola pieza. El rival deja de disputar el partido: corre detrás de una pelota que nunca le pertenece.",
    momento: "El gol a puerta vacía tras treinta pases, empujándola sin oposición.",
    req: { previo: "pitagoricos" },
    pos: { x: 960, y: 128 },
    hooks: {
      masterPosesion: { shareShift: 0.06 },
      tapIn: { zone: [4, 5], p: 0.38, bonus: 0.22, texto: "La máquina la dejó servida: solo hay que empujarla." },
    },
  },
  {
    id: "hombre_libre", filo: "posesion", rama: "firma", tier: "master", icon: "👑",
    nombre: "Hombre Libre",
    desc: "Después de tanto tejer, siempre termina apareciendo uno solo. El equipo lo encuentra, y lo que sigue es el delantero contra el arquero.",
    momento: "Veinte pases y el nueve de cara al arquero.",
    req: { previo: "osciladores" },
    pos: { x: 960, y: 275 },
    hooks: { accelFinish: { of: "circulacion", p: 0.30, bonus: 0.06,
      intro: p => `Ahí está el hombre libre: ${p.name} se suelta de la marca y queda de cara al arquero.` } },
  },

  /* Respuesta · neutralizar cualquier intento del rival */
  {
    id: "la_trampa", filo: "posesion", rama: "respuesta", tier: "basic", icon: "🪤",
    nombre: "La Trampa",
    desc: "El equipo puede devolver la pelota atrás a propósito, para sacar al rival de su bloque y volver a empezar el ataque desde otro sitio.",
    momento: "El rival saliendo a buscarla y dejando el espacio que se estaba negando.",
    req: {}, pos: { x: 190, y: 390 },
    hooks: {
      oppShotMalus: { seq: "recuperacion", bonus: -0.06,
        texto: "Mordieron el anzuelo y salieron: cuando la recuperan, están lejos y el remate no asusta." },
      backPass: { zone: [3, 5], bonus: 0.06, texto: "El equipo la devuelve atrás y vuelve a armar: el rival tiene que salir de su bloque." },
    },
  },
  {
    id: "salida_lavolpiana", filo: "posesion", rama: "respuesta", tier: "intermediate", icon: "🧩",
    nombre: "Salida Lavolpiana",
    desc: "Contra la presión alta, un mediocampista baja entre los centrales: de golpe hay un hombre más para salir y la primera línea rival queda sobrando.",
    momento: "El cinco entre los centrales y la presión rival saltando al vacío.",
    req: { previo: "la_trampa" },
    pos: { x: 450, y: 390 },
    hooks: { variantSwitch: { of: "circulacion", vsFilo: "press", p: 0.30, bonus: 0.07,
      intro: p => `SALIDA LAVOLPIANA: ${p.name} se descuelga entre los centrales y la presión rival ya no alcanza.` } },
  },
  {
    id: "la_frontera", filo: "posesion", rama: "respuesta", tier: "advanced", icon: "🚩",
    nombre: "La Frontera",
    desc: "La línea sube y se sostiene: cuando la pierden arriba y el rival busca la espalda, el equipo levanta la mano en bloque. Exige jugar con el BLOQUE ALTO: sin línea adelantada no hay trampa que tender.",
    momento: "El contragolpe rival muriendo en offside con toda la línea levantando el brazo.",
    req: { previo: "salida_lavolpiana" },
    pos: { x: 710, y: 390 },
    hooks: {
      breakawayGuard: { p: 0.40,
        texto: "La línea sube junta y lo deja en offside: la frontera aguantó y el contragolpe no existió." },
      offsideTrap: { minHeight: 4, p: 0.50, texto: "¡Trampa del offside! La línea sube junta, el brazo en alto y la contra queda anulada." },
    },
  },
  {
    id: "rest_defense", filo: "posesion", rama: "respuesta", tier: "master", icon: "👑",
    nombre: "Rest Defense",
    desc: "Incluso volcado en campo rival el equipo deja el ataque preparado para defender: la transición del rival se apaga antes de cruzar la mitad.",
    momento: "El rival recuperando la pelota y no pudiendo dar dos pases seguidos.",
    req: { previo: "la_frontera" },
    pos: { x: 960, y: 390 },
    hooks: { oppLoseActs: { zone: [2, 5], p: 0.36,
      texto: "El resto defensivo estaba armado: recuperaron, miraron arriba y no había a quién pasarla." } },
  },

  /* Expansión · transformar el dominio territorial en ocasiones */
  {
    id: "el_rondo", filo: "posesion", rama: "expansion", tier: "basic", icon: "🔄",
    nombre: "El Rondo",
    desc: "El equipo instala el rondo en campo rival y no lo suelta: el partido entero se juega donde el rival no quiere, y las piernas que corren detrás no son las nuestras.",
    momento: "Diez minutos seguidos de toque en campo rival.",
    req: {}, pos: { x: 190, y: 545 },
    hooks: {
      poolMod: { weights: { circulacion: 1.20 } },
      oppStamina: { factor: 1.10 },
    },
  },
  {
    id: "profundos", filo: "posesion", rama: "expansion", tier: "intermediate", icon: "🗡",
    nombre: "Profundos",
    desc: "Tanto toque tiene un para qué: cuando la línea rival se descuida un segundo, el pase ya salió hacia el espacio.",
    momento: "El pase filtrado que parte a la defensa después de veinte toques.",
    req: { previo: "el_rondo" },
    pos: { x: 450, y: 545 },
    hooks: { skipToFinish: { of: "circulacion", p: 0.26, bonus: 0.04,
      intro: p => `Se acabó la paciencia: ${p.name} la pincha al espacio y saltea todo el trámite.` } },
  },
  {
    id: "sorpresivos", filo: "posesion", rama: "expansion", tier: "advanced", icon: "🪂",
    nombre: "Sorpresivos",
    desc: "El equipo que toca y toca de pronto la manda por arriba: nadie lo espera, y la línea rival queda partida por el aire.",
    momento: "El pelotazo aéreo tras cuarenta toques, con la defensa adelantada.",
    req: { previo: "profundos" },
    pos: { x: 710, y: 505 },
    hooks: { variantDeep: { of: "circulacion", p: 0.30, bonus: 0.06,
      intro: p => `Sorpresa: tras tanto toque ${p.name} la manda por ARRIBA y la línea rival queda partida.` } },
  },
  {
    id: "desesperantes", filo: "posesion", rama: "expansion", tier: "advanced", icon: "😤",
    nombre: "Desesperantes",
    desc: "Perseguir la pelota sin tocarla enloquece a cualquiera. El rival termina entrando mal, y eso se cobra en tiros libres y en tarjetas.",
    momento: "El penal en el minuto ochenta tras diez minutos de sitio.",
    req: { previo: "profundos" },
    pos: { x: 710, y: 615 },
    hooks: { deepPosesion: {} },
  },
  {
    id: "polivalentes", filo: "posesion", rama: "expansion", tier: "master", icon: "👑",
    nombre: "Polivalentes",
    desc: "Delanteros que arman y mediocampistas que atacan: nadie ocupa el puesto que dice su camiseta, y la defensa rival ya no sabe a quién seguir.",
    momento: "El mediocampista definiendo de nueve mientras el nueve dio el pase.",
    req: { alguno: ["sorpresivos", "desesperantes"] },
    pos: { x: 960, y: 560 },
    hooks: { recycleUpgrade: { p: 0.60, max: 2,
      texto: "Todos juegan de todo: aparece un pasillo donde no había nadie y la posesión no muere." } },
  },
];
